### ISSUE TITLE
FPU Emulation

### ISSUE THREAD

**Issue by mrsmkl** [TrueBitFoundation/webasm-solidity#2]
Each floating point opcode should be changed into a function call. These functions implement the floating point ops with integer ops and use a fixed amount of steps, so they can be skipped by the interpreter.

Perhaps first it will be easiest to just pre-process it and always run the functions without skipping.

**Comment by mrsmkl** [comment]
Here is one C library that implements ieee floats: https://github.com/tianocore/edk2/tree/master/StdLib/LibC/Softfloat

**Comment by bloodstalker** [comment]
thanks sami.

**Comment by bloodstalker** [comment]
since the solver will be running the WASM object compiled down to native hardware machine code the first time doing the task, and will use the Truebit interpreter only when there is a challenger, we cannot guarantee undefined behaviors in regards to floating-point arithmetic in the WASM spec will always act in a specific way across all compilers across all available hardware platforms. 
hence, for the time being, we will not be supporting tasks that use floating-point instructions.
